version: '3.1'

services:

  db:
    container_name: dev_pg
    image: postgres:11.10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ejabberd
      PGDATA: /var/lib/postgresql/data/pgdata 
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    container_name: dev_redis
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
